[package]
name = "wotw_seedgen_cli"
version = "1.1.0"
edition = "2021"

[dependencies]
wotw_seedgen = { path = "../wotw_seedgen", features = ["fs", "log"] }
wotw_seedgen_stats = { path = "../wotw_seedgen_stats" }
rustc-hash = "1.1"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
log4rs = "1.1"
ansi_term = "0.12"
open = "3"
atty = "0.2"
bugsalot = "0.2"
structopt = "0.3"
sanitize-filename = "0.4"
itertools = "0.12"

[build-dependencies]
syn = "1.0"

[[bin]]
name = "seedgen"
path = "src/main.rs"
