[package]
name = "wotw_seedgen_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
wotw_seedgen = { version = "0.4", path = "../wotw_seedgen", features = ["log"] }
wotw_seedgen_stats = { version = "0.1", path = "../wotw_seedgen_stats" }
clap = { version = "4.4", features = ["derive", "string"] }
itertools = "0.12"
rand = "0.8"
serde = "1.0"
serde_json = "1.0"
strum = "0.25"
rustc-hash = "1.1"

[[bin]]
name = "seedgen"
path = "src/main.rs"
