[package]
name = "wotw_seedgen_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
wotw_seedgen = { version = "0.4", path = "../wotw_seedgen", features = ["log"] }
clap = { version = "4.4", features = ["derive"] }
rand = "0.8"
serde_json = "1.0"
