[package]
name = "wotw_seedgen_settings"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash = "1.1"
serde = { version = "1.0", optional = true, features = ["derive"] }
strum = { version = "0.25", optional = true, features = ["derive"] }
