[package]
name = "wotw_seedgen_settings"
version = "0.1.0"
edition = "2021"

[features]
parse_display = ["parse-display"]

[dependencies]
parse-display = { version = "0.8", optional = true }
rustc-hash = "1.1"
serde = { version = "1.0", optional = true, features = ["derive"] }
